baseURL = 'https://husmen.xyz/'
languageCode = 'en-us'
title = 'HUSMEN'
theme = 'academic'
publishdir = 'husmen.github.io'
ignoreErrors = ["error-remote-getcsv"]

[module]
[[module.imports]]
  path = 'github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5'